// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwgohParticipation.Data;

#nullable disable

namespace SwgohParticipation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251031233742_MakeTicketDaysNullable")]
    partial class MakeTicketDaysNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SwgohParticipation.Models.Order66Participation", b =>
                {
                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AllyCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("DiffPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("Difference")
                        .HasColumnType("int");

                    b.Property<int?>("EstimatedScore")
                        .HasColumnType("int");

                    b.Property<bool>("IsExcused")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LastActualScore")
                        .HasColumnType("int");

                    b.HasKey("StartDate", "Name");

                    b.ToTable("Order66Participations");
                });

            modelBuilder.Entity("SwgohParticipation.Models.PlayerOverview", b =>
                {
                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AllyCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CQOmiCount")
                        .HasColumnType("int");

                    b.Property<int>("CharacterGP")
                        .HasColumnType("int");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("DiscordTag")
                        .HasColumnType("longtext");

                    b.Property<int>("G11Count")
                        .HasColumnType("int");

                    b.Property<int>("G12Count")
                        .HasColumnType("int");

                    b.Property<int>("G13Count")
                        .HasColumnType("int");

                    b.Property<int>("GACOmiCount")
                        .HasColumnType("int");

                    b.Property<decimal>("GearScore")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("LeagueId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Mod6Dot")
                        .HasColumnType("int");

                    b.Property<decimal>("ModScore")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("OmiCount")
                        .HasColumnType("int");

                    b.Property<int>("Relic1Count")
                        .HasColumnType("int");

                    b.Property<int>("Relic2Count")
                        .HasColumnType("int");

                    b.Property<int>("Relic3Count")
                        .HasColumnType("int");

                    b.Property<int>("Relic4Count")
                        .HasColumnType("int");

                    b.Property<int>("Relic5Count")
                        .HasColumnType("int");

                    b.Property<int>("Relic6Count")
                        .HasColumnType("int");

                    b.Property<int>("Relic7Count")
                        .HasColumnType("int");

                    b.Property<int>("Relic8Count")
                        .HasColumnType("int");

                    b.Property<int>("Relic9Count")
                        .HasColumnType("int");

                    b.Property<int>("ShipGP")
                        .HasColumnType("int");

                    b.Property<int>("SkillRating")
                        .HasColumnType("int");

                    b.Property<int>("Speed10")
                        .HasColumnType("int");

                    b.Property<int>("Speed15")
                        .HasColumnType("int");

                    b.Property<int>("Speed20")
                        .HasColumnType("int");

                    b.Property<int>("Speed25")
                        .HasColumnType("int");

                    b.Property<int>("Star7Count")
                        .HasColumnType("int");

                    b.Property<int>("TBOmiCount")
                        .HasColumnType("int");

                    b.Property<int>("TWOmiCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UltimateGLCount")
                        .HasColumnType("int");

                    b.Property<int>("ZetaCount")
                        .HasColumnType("int");

                    b.HasKey("ReportDate", "Name");

                    b.ToTable("PlayerOverviews");
                });

            modelBuilder.Entity("SwgohParticipation.Models.RoteParticipation", b =>
                {
                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CombatWaves")
                        .HasColumnType("int");

                    b.Property<bool>("IsP1Deployed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsP1Excused")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsP2Deployed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsP2Excused")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsP3Deployed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsP3Excused")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsP4Deployed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsP4Excused")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsP5Deployed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsP5Excused")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsP6Deployed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsP6Excused")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsZeffoMissionCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("P1CombatAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P1DeployedGp")
                        .HasColumnType("int");

                    b.Property<int>("P1SpecialAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P1TerritoryPoints")
                        .HasColumnType("int");

                    b.Property<int>("P1Waves")
                        .HasColumnType("int");

                    b.Property<int>("P2CombatAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P2DeployedGp")
                        .HasColumnType("int");

                    b.Property<int>("P2SpecialAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P2TerritoryPoints")
                        .HasColumnType("int");

                    b.Property<int>("P2Waves")
                        .HasColumnType("int");

                    b.Property<int>("P3CombatAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P3DeployedGp")
                        .HasColumnType("int");

                    b.Property<int>("P3SpecialAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P3TerritoryPoints")
                        .HasColumnType("int");

                    b.Property<int>("P3Waves")
                        .HasColumnType("int");

                    b.Property<int>("P4CombatAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P4DeployedGp")
                        .HasColumnType("int");

                    b.Property<int>("P4SpecialAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P4TerritoryPoints")
                        .HasColumnType("int");

                    b.Property<int>("P4Waves")
                        .HasColumnType("int");

                    b.Property<int>("P5CombatAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P5DeployedGp")
                        .HasColumnType("int");

                    b.Property<int>("P5SpecialAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P5TerritoryPoints")
                        .HasColumnType("int");

                    b.Property<int>("P5Waves")
                        .HasColumnType("int");

                    b.Property<int>("P6CombatAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P6DeployedGp")
                        .HasColumnType("int");

                    b.Property<int>("P6SpecialAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P6TerritoryPoints")
                        .HasColumnType("int");

                    b.Property<int>("P6Waves")
                        .HasColumnType("int");

                    b.Property<int>("PlatoonUnits")
                        .HasColumnType("int");

                    b.Property<int>("RogueActions")
                        .HasColumnType("int");

                    b.Property<int>("TotalTerritoryPoints")
                        .HasColumnType("int");

                    b.HasKey("StartDate", "Name");

                    b.ToTable("RoteParticipations");
                });

            modelBuilder.Entity("SwgohParticipation.Models.TicketParticipation", b =>
                {
                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AllyCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AverageTickets")
                        .HasColumnType("int");

                    b.Property<int>("CurrentTickets")
                        .HasColumnType("int");

                    b.Property<int>("FridayTickets")
                        .HasColumnType("int");

                    b.Property<int>("LifetimeTickets")
                        .HasColumnType("int");

                    b.Property<int>("MondayTickets")
                        .HasColumnType("int");

                    b.Property<int>("SaturdayTickets")
                        .HasColumnType("int");

                    b.Property<int>("SundayTickets")
                        .HasColumnType("int");

                    b.Property<int>("ThursdayTickets")
                        .HasColumnType("int");

                    b.Property<int>("TuesdayTickets")
                        .HasColumnType("int");

                    b.Property<int>("WednesdayTickets")
                        .HasColumnType("int");

                    b.HasKey("WeekEndDate", "Name");

                    b.ToTable("TicketParticipations");
                });

            modelBuilder.Entity("SwgohParticipation.Models.TwParticipation", b =>
                {
                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AttackBanners")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DefenseBanners")
                        .HasColumnType("int");

                    b.Property<int>("MinimumBanners")
                        .HasColumnType("int");

                    b.Property<int>("TotalBanners")
                        .HasColumnType("int");

                    b.HasKey("StartDate", "Name");

                    b.ToTable("TwParticipations");
                });
#pragma warning restore 612, 618
        }
    }
}
