// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwgohParticipation.Data;

#nullable disable

namespace SwgohParticipation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SwgohParticipation.Models.Order66Participation", b =>
                {
                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("DiffPercent")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("StartDate", "Name");

                    b.ToTable("Order66Participations");
                });

            modelBuilder.Entity("SwgohParticipation.Models.RoteParticipation", b =>
                {
                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CombatWaves")
                        .HasColumnType("int");

                    b.Property<bool>("IsP1Deployed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsP2Deployed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsP3Deployed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsP4Deployed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsP5Deployed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsP6Deployed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("P1CombatAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P1DeployedGp")
                        .HasColumnType("int");

                    b.Property<int>("P1SpecialAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P1TerritoryPoints")
                        .HasColumnType("int");

                    b.Property<int>("P1Waves")
                        .HasColumnType("int");

                    b.Property<int>("P2CombatAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P2DeployedGp")
                        .HasColumnType("int");

                    b.Property<int>("P2SpecialAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P2TerritoryPoints")
                        .HasColumnType("int");

                    b.Property<int>("P2Waves")
                        .HasColumnType("int");

                    b.Property<int>("P3CombatAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P3DeployedGp")
                        .HasColumnType("int");

                    b.Property<int>("P3SpecialAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P3TerritoryPoints")
                        .HasColumnType("int");

                    b.Property<int>("P3Waves")
                        .HasColumnType("int");

                    b.Property<int>("P4CombatAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P4DeployedGp")
                        .HasColumnType("int");

                    b.Property<int>("P4SpecialAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P4TerritoryPoints")
                        .HasColumnType("int");

                    b.Property<int>("P4Waves")
                        .HasColumnType("int");

                    b.Property<int>("P5CombatAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P5DeployedGp")
                        .HasColumnType("int");

                    b.Property<int>("P5SpecialAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P5TerritoryPoints")
                        .HasColumnType("int");

                    b.Property<int>("P5Waves")
                        .HasColumnType("int");

                    b.Property<int>("P6CombatAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P6DeployedGp")
                        .HasColumnType("int");

                    b.Property<int>("P6SpecialAttempts")
                        .HasColumnType("int");

                    b.Property<int>("P6TerritoryPoints")
                        .HasColumnType("int");

                    b.Property<int>("P6Waves")
                        .HasColumnType("int");

                    b.Property<int>("PlatoonUnits")
                        .HasColumnType("int");

                    b.Property<int>("RogueActions")
                        .HasColumnType("int");

                    b.Property<int>("TotalTerritoryPoints")
                        .HasColumnType("int");

                    b.HasKey("StartDate", "Name");

                    b.ToTable("RoteParticipations");
                });

            modelBuilder.Entity("SwgohParticipation.Models.TicketParticipation", b =>
                {
                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("DailyAverage")
                        .HasColumnType("int");

                    b.HasKey("WeekEndDate", "Name");

                    b.ToTable("TicketParticipations");
                });

            modelBuilder.Entity("SwgohParticipation.Models.TwParticipation", b =>
                {
                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StartDate", "Name");

                    b.ToTable("TwParticipations");
                });
#pragma warning restore 612, 618
        }
    }
}
